### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by frizbee** [omise/spree-omise#1]
## Installation

Add this gem into your application's Gemfile
gem 'spree-omise', github: 'spree/spree-omise'

fatal: remote error:
  Repository not found.
Git error: command `git clone 'git://github.com/spree/spree-omise.git'
"/Users/username/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/cache/bundler/git/spree-omise-04cfb455237c4ef28376c074b976d0b0d631544c" --bare
--no-hardlinks --quiet` in directory /Users/username/pro/appname has failed.

Change spree to omise
gem 'spree-omise', github: 'omise/spree-omise'

**Comment by robinclart** [comment]
@frizbee It's fixed. Thanks.
