### ISSUE TITLE
undefined method `source'

### ISSUE THREAD

**Issue by frizbee** [omise/spree-omise#2]
## production.log

NoMethodError (undefined method `source' for #<Spree::CreditCard:0x007f35538e19c8>):
app/models/spree/gateway/omise.rb:70:in`update_source!'
app/models/spree/gateway/omise.rb:60:in `create_profile'
## development env

```
def update_source!(payment)
  payment.source  = CC_MAPPING[payment.source.cc_type] if CC_MAPPING.include?(payment.source.cc_type)
  payment
end
```

app/models/spree/gateway/omise.rb:70:in 'update_source!'
app/models/spree/gateway/omise.rb:60:in `create_profile'
## Parameters:

{"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"VYchU5Btwp9T0bdDeedqSZVao8CczwPDNUQ6cNJ8x6rvDVng8twEZCACggJvxguP49aVksZmTaoh6o8/2PbZ2w==",
 "order"=>{"state_lock_version"=>"3",
 "payments_attributes"=>[{"payment_method_id"=>"5"}],
 "coupon_code"=>""},
 "use_existing_card"=>"no",
 "payment_source"=>{"5"=>{"name"=>"First name Last name",
 "cc_type"=>"visa",
 "gateway_payment_profile_id"=>"tokn_test_50rf6oyichkel7bvs0s",
 "last_digits"=>"7856",
 "month"=>"8",
 "year"=>"2015"}},
 "state"=>"payment"}

**Comment by zdk** [comment]
@frizbee  Thanks for reporting! 

The fix is in PR: https://github.com/omise/spree-omise/pull/3 and already merged to master.
